### ISSUE TITLE
Redstone in the Enrichment Chamber does not create Compressed Redstone as stated in the wiki.

### ISSUE THREAD

**Issue by biggerfisch** [DungeonsAndShotguns/DS-Launcher#11]
The wiki page(http://wiki.aidancbrady.com/wiki/Compressed_Redstone) for Mekanism states that Compressed Redstone can be created by placing redstone in the Enrichment Chamber. However, this instead creates an energy upgrade, for which the proper recipe is shown here: http://wiki.aidancbrady.com/wiki/Energy_Upgrade

**Comment by F1tZ81** [comment]
This should be fixed in the next release.
