### ISSUE TITLE
Auto Updater will not work on Linux

### ISSUE THREAD

**Issue by F1tZ81** [DungeonsAndShotguns/DS-Launcher#4]
yep there is something wrong with the call in the updater that is windows specific for 7zip.

**Comment by CptSpaceToaster** [comment]
Please download and update all user applications to the latest DSUpdater.jar.  This should have been fixed 3 versions ago

If you check the internal version inside the jar, you were packaging 1.0.0.8
Version 1.0.0.13 is located in \Dropbox\DS Minecraft\Projects\TheCaptainsMods\Releases\DSUpdater

Download it here: https://dl.dropboxusercontent.com/s/mmsyd8wd8fhrsv1/DSUpdater.jar
