### ISSUE TITLE
leather crash

### ISSUE THREAD

**Issue by 7h3phr33k** [DungeonsAndShotguns/DS-Launcher#5]
When you open your inventory and NEI, search "leather", right click on leather, and start to navigate through the recipes (with arrows on top), when trying to navigate to the 3rd page it crashes the client.

http://pastebin.com/NUvUx1Ah

**Comment by CptSpaceToaster** [comment]
Paste has been removed... does the bug persist?

**Comment by F1tZ81** [comment]
Ben?

**Comment by F1tZ81** [comment]
wrong project
