### ISSUE TITLE
Thumcraft ID conflicts

### ISSUE THREAD

**Issue by F1tZ81** [DungeonsAndShotguns/DS-Launcher#7]
So, the conflict scanner didn't show this, not sure why, but there is a conflict between two items in thaumcraft. I'd fix it but I'm unable to throw out an update for people since I have no access to Jessies server.

The two ID's that conflic are the thaumium axe and the wand focus primal

I:FocusPrimal=25023
I:Thaumaxe=25023

**Comment by CptSpaceToaster** [comment]
I would bet... roughly $0.50 that your conflict scanner doesn't check for conflicts within the same .cfg  

That's just a real poor release by Thaumcraft's part...

**Comment by F1tZ81** [comment]
that is correct :)

On Fri, Apr 25, 2014 at 7:53 PM, CptSpaceToaster
notifications@github.comwrote:

> I would bet... roughly $0.50 that your conflict scanner doesn't check for
> conflicts within the same .cfg
> 
> That's just a real poor release by Thaumcraft's part...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DungeonsAndShotguns/DSLauncher/issues/7#issuecomment-41449962
> .

## 

Aaron "F1tZy" Van Prooyen

http://dungeonsandshotguns.org

**Comment by F1tZ81** [comment]
Should be fixed this release.
